name: myapp
description: A exported flutter project from FUNCTION12


# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/page-1/images/product-thumbnail.png
    - assets/page-1/images/product-thumbnail-bg.png
    - assets/page-1/images/rectangle-11.png
    - assets/page-1/images/rectangle-13-bg.png
    - assets/page-1/images/product-thumbnail-bg-FBz.png
    - assets/page-1/images/product-thumbnail-bg-7ic.png
    - assets/page-1/images/save-item-Z64.png
    - assets/page-1/images/image-6.png
    - assets/page-1/images/vector.png
    - assets/page-1/images/save-item.png
    - assets/page-1/images/ellipse-52.png
    - assets/page-1/images/like-btn.png
    - assets/page-1/images/rectangle-65.png
    - assets/page-1/images/auto-group-ggoe.png
    - assets/page-1/images/image-7.png
    - assets/page-1/images/auto-group-hdbs.png
    - assets/page-1/images/line-26.png
    - assets/page-1/images/like-btn-zKN.png
    - assets/page-1/images/like-btn-JJg.png
    - assets/page-1/images/hamburger.png
    - assets/page-1/images/image-7-ZkQ.png
    - assets/page-1/images/line-26-j96.png
    - assets/page-1/images/arrow-2.png
    - assets/page-1/images/save-item-vT6.png
    - assets/page-1/images/complete-star.png
    - assets/page-1/images/vector-d3A.png
    - assets/page-1/images/auto-group-hqxe.png
    - assets/page-1/images/edit-btn.png
    - assets/page-1/images/rectangle-8-bg.png
    - assets/page-1/images/navbar.png
    - assets/page-1/images/polygon-1.png
    - assets/page-1/images/auto-group-a132.png
    - assets/page-1/images/vector-rur.png
    - assets/page-1/images/image-6-zmA.png
    - assets/page-1/images/group-33.png
    - assets/page-1/images/save-item-Xm6.png
    - assets/page-1/images/product-thumbnail-bg-gtt.png
    - assets/page-1/images/edit-btn-YS8.png
    - assets/page-1/images/auto-group-7b1v.png
    - assets/page-1/images/polygon-1-X3A.png
    - assets/page-1/images/back-button.png
    - assets/page-1/images/auto-group-plaq.png
    - assets/page-1/images/ellipse-50.png
    - assets/page-1/images/product-thumbnail-bg-XhN.png
    - assets/page-1/images/auto-group-gujy.png
    - assets/page-1/images/like-btn-1Me.png
    - assets/page-1/images/complete-star-NCC.png
    - assets/page-1/images/back-button-8SG.png
    - assets/page-1/images/image-5.png
    - assets/page-1/images/auto-group-wch2.png
    - assets/page-1/images/product-thumbnail-bg-ieG.png
    - assets/page-1/images/auto-group-zwgk.png
    - assets/page-1/images/ellipse-51.png
    - assets/page-1/images/line-25.png
    - assets/page-1/images/arrow-1.png
    - assets/page-1/images/rectangle-8-bg-MqW.png
    - assets/page-1/images/ellipse-50-WCc.png
    - assets/page-1/images/auto-group-gftg.png
    - assets/page-1/images/like-btn-cmS.png
    - assets/page-1/images/save-item-y9E.png
    - assets/page-1/images/ellipse-50-Koz.png
    - assets/page-1/images/save-item-GUL.png
    - assets/page-1/images/progress-bar.png
    - assets/page-1/images/auto-group-ufpr.png
    - assets/page-1/images/back-button-mfz.png
    - assets/page-1/images/rectangle-11-bg.png
    - assets/page-1/images/product-thumbnail-vBW.png
    - assets/page-1/images/save-item-xx4.png
    - assets/page-1/images/auto-group-1vp4.png
    - assets/page-1/images/hamburger-c4k.png
    - assets/page-1/images/save-item-YUC.png
    - assets/page-1/images/auto-group-cpsl.png
    - assets/page-1/images/progress-bar-o9E.png
    - assets/page-1/images/selected-card-indicator.png
    - assets/page-1/images/group-32.png
    - assets/page-1/images/auto-group-eigk.png
    - assets/page-1/images/line-26-s96.png
    - assets/page-1/images/save-item-dPA.png
    - assets/page-1/images/mask-group.png
    - assets/page-1/images/auto-group-ksdn.png
    - assets/page-1/images/arrow-1-miC.png
    - assets/page-1/images/line-25-Kji.png
    - assets/page-1/images/line-25-HRe.png
    - assets/page-1/images/save-item-Erg.png
    - assets/page-1/images/save-item-bx8.png
    - assets/page-1/images/group-33-WJQ.png
    - assets/page-1/images/google.png
    - assets/page-1/images/image-3-bg.png
    - assets/page-1/images/back-button-orC.png
    - assets/page-1/images/back-button-Crx.png
    - assets/page-1/images/chip.png
    - assets/page-1/images/ellipse-51-pQL.png
    - assets/page-1/images/polygon-1-sJ4.png
    - assets/page-1/images/save-item-XWL.png
    - assets/page-1/images/rectangle-13.png
    - assets/page-1/images/mask-group-NoE.png
    - assets/page-1/images/product-thumbnail-bg-R1N.png
    - assets/page-1/images/navbar-ZdN.png
    - assets/page-1/images/rectangle-11-bg-W7v.png
    - assets/page-1/images/back-button-md6.png
    - assets/page-1/images/chip-cWY.png
    - assets/page-1/images/product-thumbnail-bg-oXi.png
    - assets/page-1/images/rectangle-13-bg-Jqi.png
    - assets/page-1/images/auto-group-rrap.png
    - assets/page-1/images/navbar-hXi.png
    - assets/page-1/images/mask-group-BMW.png
    - assets/page-1/images/selected-card-indicator-KEc.png
    - assets/page-1/images/chip-twv.png
    - assets/page-1/images/progress-indicator.png
    - assets/page-1/images/image-4-bg.png
    - assets/page-1/images/chip-wwr.png
    - assets/page-1/images/mask-group-EbE.png
    - assets/page-1/images/back-button-Q2G.png
    - assets/page-1/images/rectangle-65-CZS.png
    - assets/page-1/images/clarity-success-standard-solid.png
    - assets/page-1/images/progress-indicator-bCp.png
    - assets/page-1/images/product-thumbnail-zoE.png
    - assets/page-1/images/rectangle-16.png
    - assets/page-1/images/rectangle-8-bg-ida.png
    - assets/page-1/images/navbar-htQ.png
    - assets/page-1/images/rectangle-19-bg.png
    - assets/page-1/images/rectangle-11-bg-iSQ.png
    - assets/page-1/images/rectangle-13-bg-xnQ.png
    - assets/page-1/images/vector-rMz.png
    - assets/page-1/images/back-button-EYt.png
    - assets/page-1/images/hamburger-Wep.png
    - assets/page-1/images/auto-group-9jr6.png
    - assets/page-1/images/auto-group-mmzw.png
    - assets/page-1/images/ellipse-29-bg.png
    - assets/page-1/images/back-button-4aG.png
    - assets/page-1/images/vector-yUG.png
    - assets/page-1/images/auto-group-gzkx.png
    - assets/page-1/images/auto-group-sqiu.png
    - assets/page-1/images/auto-group-pk9n.png
    - assets/page-1/images/auto-group-xqbj.png
    - assets/page-1/images/navmenu.png
    - assets/page-1/images/auto-group-q9a4.png
    - assets/page-1/images/vector-164.png
    - assets/page-1/images/ellipse-15-bg.png
    - assets/page-1/images/ellipse-25-bg.png
    - assets/page-1/images/navmenu-cvx.png
    - assets/page-1/images/hamburger-zpC.png
    - assets/page-1/images/image-9.png
    - assets/page-1/images/vector-N52.png
    - assets/page-1/images/close-.png
    - assets/page-1/images/ellipse-27-bg.png
    - assets/page-1/images/hamburger-ewe.png
    - assets/page-1/images/vector-ZQg.png
    - assets/page-1/images/save-item-WSp.png
    - assets/page-1/images/ellipse-37.png
    - assets/page-1/images/ellipse-17-bg.png
    - assets/page-1/images/ellipse-36.png
    - assets/page-1/images/ellipse-13-bg.png
    - assets/page-1/images/user-image-bg.png
    - assets/page-1/images/vector-gUL.png
    - assets/page-1/images/vector-8Hi.png
    - assets/page-1/images/ellipse-19-bg.png
    - assets/page-1/images/ellipse-11-bg.png
    - assets/page-1/images/navbar-hJC.png
    - assets/page-1/images/ellipse-35-bg.png
    - assets/page-1/images/ellipse-23-bg.png
    - assets/page-1/images/back-button-D6c.png
    - assets/page-1/images/save-item-TQG.png
    - assets/page-1/images/save-item-nBe.png
    - assets/page-1/images/vector-KjJ.png
    - assets/page-1/images/image-12.png
    - assets/page-1/images/search.png
    - assets/page-1/images/focus-selector.png
    - assets/page-1/images/ellipse-21-bg.png
    - assets/page-1/images/vector-1Xz.png
    - assets/page-1/images/image-13.png
    - assets/page-1/images/vector-oNt.png
    - assets/page-1/images/image-5-wwa.png
    - assets/page-1/images/waves.png
    - assets/page-1/images/vector-i8C.png
    - assets/page-1/images/back-button-osi.png
    - assets/page-1/images/image-8.png
    - assets/page-1/images/vector-tQk.png
    - assets/page-1/images/vector-fTS.png
    - assets/page-1/images/vector-Hj2.png
    - assets/page-1/images/cam-field-bg.png
    - assets/page-1/images/hamburger-uCG.png
    - assets/page-1/images/image-10.png
    - assets/page-1/images/vector-vm2.png
    - assets/page-1/images/rectangle-55-bg.png
    - assets/page-1/images/image-11.png
    - assets/page-1/images/back-button-Hac.png
    - assets/page-1/images/back-button-QPN.png
    - assets/page-1/images/social-login.png
    - assets/page-1/images/social-login-MPr.png
    - assets/page-1/images/social-login-YW8.png
    - assets/page-1/images/vector-s64.png
    - assets/page-1/images/rectangle-56-bg.png
    - assets/page-1/images/email-text-field.png
    - assets/page-1/images/back-button-YdJ.png
    - assets/page-1/images/rectangle-57-bg.png
    - assets/page-1/images/vector-q8G.png
    - assets/page-1/images/save-item-6jn.png
    - assets/page-1/images/save-item-ELC.png
    - assets/page-1/images/vector-u64.png
    - assets/page-1/images/vector-1yE.png
    - assets/page-1/images/xp-diy.png
    - assets/page-1/images/hamburger-r1r.png
    - assets/page-1/images/vector-smv.png
    - assets/page-1/images/vector-yt8.png
    - assets/page-1/images/vector-HKi.png
    - assets/page-1/images/vector-msr.png
    - assets/page-1/images/vector-1.png
    - assets/page-1/images/save-item-2fn.png
    - assets/page-1/images/vector-39n.png
    - assets/page-1/images/vector-irp.png
    - assets/page-1/images/vector-GZS.png
    - assets/page-1/images/vector-iGC.png
    - assets/page-1/images/vector-cmz.png
    - assets/page-1/images/vector-s7z.png
    - assets/page-1/images/vector-ZTA.png
    - assets/page-1/images/vector-FDE.png
    - assets/page-1/images/vector-dun.png
    - assets/page-1/images/mu-account-btn.png
    - assets/page-1/images/vector-1gg.png
    - assets/page-1/images/vector-s8G.png
    - assets/page-1/images/vector-WjW.png
    - assets/page-1/images/vector-E2Y.png
    - assets/page-1/images/xp-diy-S3n.png
    - assets/page-1/images/at-at-21.png
    - assets/page-1/images/vector-aWY.png
    - assets/page-1/images/vector-dNL.png
    - assets/page-1/images/save-item-Xyv.png
    - assets/page-1/images/vector-WHJ.png
    - assets/page-1/images/navbar-VVe.png
    - assets/page-1/images/vector-3Fa.png
    - assets/page-1/images/vector-Bbz.png
    - assets/page-1/images/.png
    - assets/page-1/images/vector-UAx.png
    - assets/page-1/images/save-item-5eC.png
    - assets/page-1/images/save-item-wkG.png
    - assets/page-1/images/vector-Bk8.png
    - assets/page-1/images/vector-RuN.png
    - assets/page-1/images/save-item-kya.png
    - assets/page-1/images/vector-pv8.png
    - assets/page-1/images/vector-h48.png
    - assets/page-1/images/vector-8yJ.png
    - assets/page-1/images/vector-PWU.png
    - assets/page-1/images/rectangle-60.png
    - assets/page-1/images/vector-fJc.png
    - assets/page-1/images/vector-CWp.png
    - assets/page-1/images/search-FVe.png
    - assets/page-1/images/-o1N.png
    - assets/page-1/images/vector-Pr4.png
    - assets/page-1/images/vector-tdi.png
    - assets/page-1/images/vector-eHJ.png
    - assets/page-1/images/vector-jWL.png
    - assets/page-1/images/vector-vYC.png
    - assets/page-1/images/vector-eEY.png
    - assets/page-1/images/vector-r7e.png
    - assets/page-1/images/rectangle-60-TsS.png
    - assets/page-1/images/save-item-kE8.png
    - assets/page-1/images/vector-LmA.png
    - assets/page-1/images/vector-zgc.png
    - assets/page-1/images/vector-yk8.png
    - assets/page-1/images/vector-Jck.png
    - assets/page-1/images/vector-7s2.png
    - assets/page-1/images/vector-ZbS.png
    - assets/page-1/images/save-item-Uf6.png
    - assets/page-1/images/save-item-DbA.png
    - assets/page-1/images/save-item-uVe.png
    - assets/page-1/images/vector-5Nc.png
    - assets/page-1/images/vector-Mkg.png
    - assets/page-1/images/vector-fRn.png
    - assets/page-1/images/k-9-the-canine.png
    - assets/page-1/images/save-item-N1r.png
    - assets/page-1/images/vector-7sz.png
    - assets/page-1/images/vector-LRS.png
    - assets/page-1/images/user-image.png
    - assets/page-1/images/auto-group-nvk4.png
    - assets/page-1/images/save-item-C7n.png
    - assets/page-1/images/rectangle-8-bg-X5e.png
    - assets/page-1/images/vector-sqN.png
    - assets/page-1/images/vector-Wbv.png
    - assets/page-1/images/vector-fUp.png
    - assets/page-1/images/save-item-Nz8.png
    - assets/page-1/images/product-thumbnail-bg-zEp.png
    - assets/page-1/images/rectangle-60-3A4.png
    - assets/page-1/images/vector-aMS.png
    - assets/page-1/images/rectangle-60-4PE.png
    - assets/page-1/images/property-1variant3.png
    - assets/page-1/images/property-1default.png
    - assets/page-1/images/property-1variant2.png
    - assets/page-1/images/product-thumbnail-bg-eov.png
    - assets/page-1/images/save-item-R32.png
    - assets/page-1/images/vector-xNQ.png
    - assets/page-1/images/chat-bot.png
    - assets/page-1/images/product-thumbnail-bg-fmn.png
    - assets/page-1/images/image-3-bg-aBe.png
    - assets/page-1/images/image-5-bg.png
    - assets/page-1/images/image-6-bg.png
    - assets/page-1/images/image-4-bg-aua.png
    - assets/page-1/images/image-3-bg-4VA.png
    - assets/page-1/images/image-2.png
    - assets/page-1/images/product-thumbnail-pcU.png
    - assets/page-1/images/image-5-bg-VTr.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
